config/routes.rb
Rails.application.routes.draw do
  root 'leads#index'
  resources :leads, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  # before_create :parse_phone
  
  validates :first_name, :last_name, :phone_number, :message, presence: true
  # validates :phone_number, phone: true

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def parse_phone
    self.phone_number = Phonelib.parse(phone_number).full_e164.presence
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def index
    @leads = Lead.all
  end

  def new
    @lead = Lead.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    lead = Lead.create(lead_params)
    if lead.valid?
      TwilioClient.new.send_text(lead)
      flash[:message] = "Lead, #{lead.full_name}, was succesfully created!"
    else
      flash[:errors] = lead.errors.full_messages
    end
    redirect_to leads_path
  end

  private
  def lead_params
    params.require(:lead).permit(:first_name, :last_name, :phone_number, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lead_helper.rb
module LeadHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pingsurance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/97011dda0d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/leads/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Add New Lead</h4>
</div>
<div class="modal-body">
  <div class="card-body">
    <% if flash[:message] %>
      <%= flash[:message] %>
    <% end %>
    <%= form_for @lead do |f|%>
      <div class="form-group row">
          <%= f.label :first_name, "First Name", :class => "col-sm-4 col-form-label"%>
        <div class="col-sm-8">
          <%= f.text_field :first_name, :class => "form-control", :placeholder => "Enter First Name"%>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :last_name, "Last Name", :class => "col-sm-4 col-form-label"%>
        <div class="col-sm-8">
          <%= f.text_field :last_name, :class => "form-control", :placeholder => "Enter Last Name"%>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :phone_number, "Phone Number", :class => "col-sm-4 col-form-label"%>
        <div class="col-sm-8">
          <%= f.phone_field :phone_number, {:class => "form-control", :placeholder => "123-456-7890", :pattern => "[0-9]{3}-[0-9]{3}-[0-9]{4}"}%>
        </div>
      </div>
      <div class="form-group row">
        <% f.label :message, :class => "col-sm-4 col-form-label"%>
        <div class="col-sm-12">
          <%= f.text_area :message, :class => "form-control", :placeholder => "Enter Message"%>
        </div>
      </div>
      <%= f.submit 'Create & Send', :class => "btn btn-success float-right" %>
      <button type="button" class="btn btn-danger float-right mr-3" data-dismiss="modal">Cancel</button>
  <% end %>
</div>

app/views/leads/index.html.erb
<div class="container">
  <h1 class='mt-3'>Pingsurance</h1>

  <%= link_to '<i class="fas fa-user-plus fa-3x mr-2"></i> Add New Lead'.html_safe, new_lead_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-outline-dark my-3'}%>
  
  <% if flash[:message] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:message] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <div class="alert alert-danger" role="alert">
        <%= error %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  <% end %>
  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

  <table class='table table-striped table-bordered table-hover'>
    <thead class='thead-dark'>
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Date Texted</th>
      </tr>
    </thead>
    <tbody>
      <% @leads.each do |lead| %>
        <tr>
          <td><%= lead.full_name %></td>
          <td><%= lead.phone_number %></td>
          <td><%= lead.created_at.strftime("%m/%d/%Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/leads/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();